-- Remove RLS (Row Level Security) de todas as tabelas
ALTER TABLE divergencias DISABLE ROW LEVEL SECURITY;
ALTER TABLE execucoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE fichas_presenca DISABLE ROW LEVEL SECURITY;
ALTER TABLE guias DISABLE ROW LEVEL SECURITY;
ALTER TABLE carteirinhas DISABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes DISABLE ROW LEVEL SECURITY;
ALTER TABLE planos_saude DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE auditoria_execucoes DISABLE ROW LEVEL SECURITY;

-- Garante que o usuário anon tem acesso total (para desenvolvimento)
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon;
